common: &default_settings
  license_key: '62cff396b11ba705b7e70de47ec3186c556e9af8'
  app_name: Racing on Rails

  monitor_mode: true
  developer_mode: false
  log_level: info
  capture_params: true

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500

  error_collector:
    enabled: true
    capture_source: true
    ignore_errors: ActionController::RoutingError

development:
  <<: *default_settings
  monitor_mode: false
  app_name: Racing on Rails Development

test:
  <<: *default_settings
  monitor_mode: false
  app_name: Racing on Rails Test

acceptance:
  <<: *default_settings
  monitor_mode: false
  app_name: Racing on Rails Acceptance

staging:
  <<: *default_settings
  monitor_mode: true
  app_name: Racing on Rails Staging

production:
  <<: *default_settings
  monitor_mode: true
